export const SURY_TREASURY_ABI = [
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTreasurySummary',
    inputs: [],
    outputs: [
      { name: 'balance', type: 'uint256' },
      { name: 'totalDeposited', type: 'uint256' },
      { name: 'totalSpent', type: 'uint256' },
      { name: 'todaySpend', type: 'uint256' },
      { name: 'isPaused', type: 'bool' },
      { name: 'owner', type: 'address' },
      { name: 'agentCount', type: 'uint256' },
      { name: 'taskCount', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAgent',
    inputs: [{ name: 'agentId', type: 'uint256' }],
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'name', type: 'string' },
          { name: 'agentAddress', type: 'address' },
          { name: 'assignedBudget', type: 'uint256' },
          { name: 'remainingBudget', type: 'uint256' },
          { name: 'spent', type: 'uint256' },
          { name: 'dailyLimit', type: 'uint256' },
          { name: 'perTransactionLimit', type: 'uint256' },
          { name: 'policyId', type: 'uint256' },
          { name: 'taskCount', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'expiry', type: 'uint256' },
          { name: 'lastDay', type: 'uint256' },
          { name: 'dailySpent', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPolicy',
    inputs: [{ name: 'policyId', type: 'uint256' }],
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'agentId', type: 'uint256' },
          { name: 'budget', type: 'uint256' },
          { name: 'perTransactionLimit', type: 'uint256' },
          { name: 'dailyLimit', type: 'uint256' },
          { name: 'approvedTokens', type: 'address[]' },
          { name: 'approvedTargets', type: 'address[]' },
          { name: 'expiry', type: 'uint256' },
          { name: 'status', type: 'uint8' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTask',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'agentId', type: 'uint256' },
          { name: 'description', type: 'string' },
          { name: 'amount', type: 'uint256' },
          { name: 'token', type: 'address' },
          { name: 'destination', type: 'address' },
          { name: 'target', type: 'address' },
          { name: 'policyId', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'expiry', type: 'uint256' },
        ],
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createTask',
    inputs: [
      { name: 'agentId', type: 'uint256' },
      { name: 'description', type: 'string' },
      { name: 'amount', type: 'uint256' },
      { name: 'token', type: 'address' },
      { name: 'destination', type: 'address' },
      { name: 'target', type: 'address' },
      { name: 'expiry', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approveTask',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rejectTask',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'executeTask',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'TaskCreated',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'agentId', type: 'uint256' },
      { indexed: false, name: 'description', type: 'string' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'destination', type: 'address' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'TaskApproved',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'approvedBy', type: 'address' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'PaymentExecuted',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'agentId', type: 'uint256' },
      { indexed: true, name: 'recipient', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'token', type: 'address' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
  },
] as const;
